dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk12
  - openjdk8
  - openjdk12

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

before_install:
  - chmod +x gradlew
