
name: Build and run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  EXECUTABLE_JAR: "cruxCometPercolator2LimelightXML.jar"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '${{matrix.jdk}}'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Run executable
      run: java -jar build/libs/${{ env.EXECUTABLE_JAR }} -h
